### ISSUE TITLE
Provide package.json and JSONCrush in a cjs, es, umd module variants

### ISSUE THREAD

**Issue by darcyparker** [KilledByAPixel/JSONCrush#12]
This has been asked in various ways in:

* https://github.com/KilledByAPixel/JSONCrush/pull/10
* https://github.com/KilledByAPixel/JSONCrush/pull/2
* https://github.com/KilledByAPixel/JSONCrush/issues/8
* https://github.com/dprothero/JSONCrush (which is associated with `npm install JSONCrush`) added a commit with ESM `export` syntax.

Having cjs, es, umd variants that people can choose from would be very helpful.

Perhaps the previous pull requests are doing too much or aren't the right approach for your taste?  But there's still the challenge of getting started quickly with JSONCrush in various JS environments.

Maybe a more amicable approach would be to create a simple build script to wrap `JSONCrush.js` in these 3 module types?  Before I put in the effort, would you consider such a pull request?

(Things like babel/typescript are nice... so some meta data in the `package.json` to help those tools would be nice. But in my opinion, its not critical to provide many builds JSONCrush in ES3/ES5 and minified flavors.  That can be left to build tools the downstream users setup.  But having a few of the standard module formats would be helpful for someone who wants to quickly import the module to evaluate it.)

**Comment by KilledByAPixel** [comment]
the next step that i am comfortable with is getting back control of the npm and adding modules and package.json, after that maybe  more but i think i need to start there.,

**Comment by antialias** [comment]
> the next step that i am comfortable with is getting back control of the npm

Did you ever have control of "the npm"? Looks like @dprothero [`cloned this repo`](https://github.com/dprothero/JSONCrush) and [published your package](https://www.npmjs.com/package/jsoncrush) for you because you never did.

> and adding ... package.json

run `npm init` and you're done.

Since it's been over six months since this issue was opened, consider publishing from your own namespace in order to un-block this ticket.

**Comment by antialias** [comment]
The ask in this ticket can be accomplished with a rollup config and a `prepublish` script in your (currently nonexistent) `package.json`. It's a 10 minute job.

**Comment by darcyparker** [comment]
https://github.com/KilledByAPixel/JSONCrush/pull/13 solves it... The pull request just needs to be reviewed / merged.

**Comment by KilledByAPixel** [comment]
Just pushed out a major update to JSONCrush that wraps it in a module, adds package.json, and is now updated on NPM!

https://www.npmjs.com/package/jsoncrush

**Comment by antialias** [comment]
> Just pushed out a major update to JSONCrush that wraps it in a module, adds package.json, and is now updated on NPM!

well that's a start, but if there is any intention for this package to be maintained we really need the build script to be included in this repository and for it to automatically run whenever `npm publish` is run.
