### ISSUE TITLE
Unable to shorten generated URLs, ver2

### ISSUE THREAD

**Issue by microbecode** [KilledByAPixel/JSONCrush#20]
My previous issue (https://github.com/KilledByAPixel/JSONCrush/issues/19) was closed without fixing the issue, so I'm opening a new one.

As I stated in my original issue, the problem is not in the last character, but in the 'header start' character used as a separator. Here's a shorter example: `https://example.com/("a!true, "b!"hello")!": !J`

Entering the above URL to a service such as tinyurl.com gives you a tinyurl, but it doesn't work. If you remove the special character from the URL, the tinyurl works again.

**Comment by microbecode** [comment]
I was also trying to read specifications about which characters are allowed in URLs. The specifications are a tad... difficult to read, but I don't see any mention of the special character being allowed generally. Yes, (some) browsers may accept it, but currently it seems to me that it's not in the standard.
Reference for example: https://stackoverflow.com/questions/1856785/characters-allowed-in-a-url

**Comment by KilledByAPixel** [comment]
Sorry, I didn't understand your issue.

You must call encodeURIComponent on the string before including it in a url. This needs to be done for every string you include in a url, not just JSONCrush. it is necessary to escape certain characters.

**Comment by microbecode** [comment]
Ah right, thanks. I somehow had the impression that the library would already produce URL-compatible strings, and didn't think of it further. I recommend adding a note about this in the readme.

**Comment by KilledByAPixel** [comment]
ok, i will do that. glad you got it working, thanks!
