### ISSUE TITLE
How safe is this algorithm to use on production? Are there unit tests validating that it is working well in all cases?

### ISSUE THREAD

**Issue by vladferix** [KilledByAPixel/JSONCrush#3]

**Comment by KilledByAPixel** [comment]
It is very safe imo. The code is very small with little room for error and it would be easy to remove or change if there was a problem. It is also based on JSCrush which has been in used to compress hundreds of javascript demos.

I have done testing on every type of string I could think of. I will add a unit test that iterates through a list of strings, crushes, uncrushes, and displays test results.

**Comment by KilledByAPixel** [comment]
I added some basic unit tests on the demo page at https://killedbyapixel.github.io/JSONCrush

While doing this I discovered that some emojis aren't compressed properly (surrogate pairs) so I fixed that.

Let me know if I missed anything that should be included in the unit tests.
